/*******************************************************************************

    locals.js - OpenRouter 中文化插件词库
    Copyright (C) 2025-2026 小龙虾
    License: MIT

    Home: https://github.com/chiablue/openrouter-chinese
*/
var I18N = {};

I18N.conf = {
    rePagePath: /^\/($|chat\/[^\/]+|models|discover|account|api-keys|billing|usage|auth\/login|auth\/callback|docs|pricing|about|blog|careers|terms|privacy|enterprise|contact)/,

    // 字符数据监测页面
    characterDataPage: ['chat', 'models', 'discover', 'account', 'api-keys', 'billing', 'usage'],

    // 忽略突变元素规则
    ignoreMutationSelectorPage: {
        'chat': [
            '.cm-line',
            '.cm-content',
            '.ProseMirror',
        ],
        'models': [
            '.model-price',
            '.token-display',
        ],
        '*': [
            '.search-input',
            '.query-builder',
            'span[data-testid="search-keyword"]',
        ],
    },

    // 忽略元素规则
    ignoreSelectorPage: {
        'chat': [
            '.chat-message-code',
            '.code-block',
            '.token-count',
            '.model-name',
            '.provider-name',
        ],
        'models': [
            '.model-id',
            '.context-window',
            '.max-input',
            '.max-output',
            '.pricing-per-1k',
            '.api-endpoint',
        ],
        'account': [
            '.user-email',
            '.api-key-value',
            '.user-id',
        ],
        '*': [
            'CODE', 'SCRIPT', 'STYLE', 'LINK', 'IMG', 'PRE', 'KBD', 'SVG',
            '.search-match',
            '.highlight',
            '.token-counter',
        ],
    },
};

I18N["zh-CN"] = {};

I18N["zh-CN"]["title"] = {
    "static": {
        "OpenRouter - AI API统一接口": "OpenRouter - AI API统一接口",
        "Login · OpenRouter": "登录 · OpenRouter",
        "Sign Up · OpenRouter": "注册 · OpenRouter",
        "Models · OpenRouter": "模型列表 · OpenRouter",
        "Chat · OpenRouter": "聊天 · OpenRouter",
        "API Keys · OpenRouter": "API密钥 · OpenRouter",
        "Account Settings · OpenRouter": "账户设置 · OpenRouter",
        "Billing · OpenRouter": "账单 · OpenRouter",
        "Usage · OpenRouter": "使用统计 · OpenRouter",
        "Pricing · OpenRouter": "价格 · OpenRouter",
        "Discover · OpenRouter": "发现 · OpenRouter",
        "Docs · OpenRouter": "文档 · OpenRouter",
        "About · OpenRouter": "关于 · OpenRouter",
        "Blog · OpenRouter": "博客 · OpenRouter",
        "Careers · OpenRouter": "招聘 · OpenRouter",
        "Terms of Service · OpenRouter": "服务条款 · OpenRouter",
        "Privacy Policy · OpenRouter": "隐私政策 · OpenRouter",
        "Enterprise · OpenRouter": "企业版 · OpenRouter",
        "Contact · OpenRouter": "联系我们 · OpenRouter",
    },
    "regexp": [
        [/^OpenRouter - .*/, "OpenRouter - $1"],
        [/(.*) · OpenRouter/, "$1 · OpenRouter"],
        [/\/(models)\//i, " / 模型 /"],
        [/\/(chat)\//i, " / 聊天 /"],
        [/\/(account)\//i, " / 账户 /"],
        [/\/(api-keys)\//i, " / API密钥 /"],
        [/\/(billing)\//i, " / 账单 /"],
        [/\/(usage)\//i, " / 使用统计 /"],
        [/\/(discover)\//i, " / 发现 /"],
        ["_regexp_end", "end"]
    ],
};

I18N["zh-CN"]["public"] = {
    "static": {
        // 导航栏
        "Models": "模型列表",
        "Chat": "聊天",
        "Discover": "发现",
        "Account": "账户",
        "Pricing": "价格",
        "Docs": "文档",
        "Sign In": "登录",
        "Sign Up": "注册",
        "Log out": "退出登录",

        // 顶部横幅
        "Welcome to OpenRouter": "欢迎来到 OpenRouter",
        "Get started by adding credits to your account.": "开始使用，请先为您的账户充值。",
        "Add Credits": "充值",
        "Add Funds": "充值",

        // 底部
        "About": "关于",
        "Blog": "博客",
        "Careers": "招聘",
        "Terms": "服务条款",
        "Privacy": "隐私政策",
        "Security": "安全",
        "Status": "状态",
        "Community": "社区",
        "Contact": "联系我们",
        "Manage cookies": "管理 Cookie",
        "Do not share my personal information": "不分享我的个人信息",

        // 按钮和操作
        "Submit": "提交",
        "Cancel": "取消",
        "Save": "保存",
        "Delete": "删除",
        "Edit": "编辑",
        "Create": "创建",
        "New": "新建",
        "Copy": "复制",
        "Close": "关闭",
        "Confirm": "确认",
        "Back": "返回",
        "Next": "下一步",
        "Previous": "上一步",
        "Continue": "继续",
        "Learn more": "了解更多",
        "View all": "查看全部",
        "Show more": "显示更多",
        "Show less": "显示更少",

        // 状态和提示
        "Loading": "加载中…",
        "Loading...": "加载中…",
        "Error": "错误",
        "Success": "成功",
        "Warning": "警告",
        "Info": "信息",
        "Search": "搜索",
        "Filter": "过滤",
        "Sort by": "排序",
        "All": "全部",
        "None": "无",
        "N/A": "不适用",
        "Yes": "是",
        "No": "否",
        "Enable": "启用",
        "Disable": "禁用",
        "On": "开",
        "Off": "关",

        // 时间和日期
        " seconds ago": "秒前",
        " second ago": "秒前",
        " minutes ago": "分钟前",
        " minute ago": "分钟前",
        " hours ago": "小时前",
        " hour ago": "小时前",
        " days ago": "天前",
        " day ago": "天前",
        " ago": "前",
        "Just now": "刚刚",
        "Today": "今天",
        "Yesterday": "昨天",
        "Tomorrow": "明天",
        "Jan": "一月",
        "Feb": "二月",
        "Mar": "三月",
        "Apr": "四月",
        "May": "五月",
        "Jun": "六月",
        "Jul": "七月",
        "Aug": "八月",
        "Sep": "九月",
        "Oct": "十月",
        "Nov": "十一月",
        "Dec": "十二月",
        "January": "一月",
        "February": "二月",
        "March": "三月",
        "April": "四月",
        "May": "五月",
        "June": "六月",
        "July": "七月",
        "August": "八月",
        "September": "九月",
        "October": "十月",
        "November": "十一月",
        "December": "十二月",
        "Mon": "周一",
        "Tue": "周二",
        "Wed": "周三",
        "Thu": "周四",
        "Fri": "周五",
        "Sat": "周六",
        "Sun": "周日",
        "Monday": "星期一",
        "Tuesday": "星期二",
        "Wednesday": "星期三",
        "Thursday": "星期四",
        "Friday": "星期五",
        "Saturday": "星期六",
        "Sunday": "星期日",

        // 通用表单
        "Required": "必填",
        "Optional": "可选",
        "Required field": "必填字段",
        "Invalid input": "输入无效",
        "Please enter a valid": "请输入有效的",
        "Please select a": "请选择一个",
        "This field is required": "此字段为必填",

        // 错误消息
        "Something went wrong": "出错了",
        "Please try again": "请重试",
        "An error occurred": "发生错误",
        "Network error": "网络错误",
        "Connection failed": "连接失败",
        "Timeout": "超时",
        "Forbidden": "禁止访问",
        "Unauthorized": "未授权",
        "Not found": "未找到",

        // 认证相关
        "Email": "邮箱",
        "Password": "密码",
        "Confirm password": "确认密码",
        "Forgot password?": "忘记密码?",
        "Reset password": "重置密码",
        "Verification code": "验证码",
        "Two-factor authentication": "双因素认证",
        "Enter verification code": "输入验证码",
        "Verify": "验证",
        "Remember me": "记住我",
        "Don't have an account?": "还没有账户?",
        "Already have an account?": "已有账户?",
        "Sign in": "登录",
        "Sign up": "注册",
        "Create account": "创建账户",

        // 模型相关
        "Model": "模型",
        "Provider": "提供商",
        "Context Window": "上下文窗口",
        "Max Input": "最大输入",
        "Max Output": "最大输出",
        "Pricing": "价格",
        "Price per 1K tokens": "每1K tokens价格",
        "Input": "输入",
        "Output": "输出",
        "Free": "免费",
        "From": "起",
        "per 1K tokens": "每1K tokens",
        "per million tokens": "每百万tokens",
        "context": "上下文",
        "tokens": "tokens",
        "params": "参数",
        "parameters": "参数",
        "billion": "B",

        // API密钥
        "API Key": "API密钥",
        "API Keys": "API密钥",
        "Create new key": "创建新密钥",
        "Key name": "密钥名称",
        "Your API keys": "您的API密钥",
        "No API keys yet": "还没有API密钥",
        "Key created": "密钥已创建",
        "Key deleted": "密钥已删除",
        "Are you sure you want to delete this key?": "确定要删除此API密钥吗?",
        "Key will be removed permanently": "密钥将被永久删除",
        "Copy key": "复制密钥",
        "Show key": "显示密钥",
        "Hide key": "隐藏密钥",
        "Created": "创建时间",
        "Last used": "最后使用",
        "Never used": "从未使用",

        // 聊天界面
        "Send a message": "发送消息",
        "Type your message...": "输入您的消息...",
        "Enter your message": "输入消息",
        "Chat": "聊天",
        "New chat": "新建聊天",
        "Clear chat": "清空聊天",
        "Delete chat": "删除聊天",
        "Rename chat": "重命名聊天",
        "Model": "模型",
        "Select a model": "选择模型",
        "Temperature": "温度",
        "Top P": "Top P",
        "Max tokens": "最大tokens",
        "Stop sequences": "停止序列",
        "System prompt": "系统提示",
        "Stream response": "流式响应",
        "Send": "发送",
        "Stop": "停止",
        "Regenerate": "重新生成",
        "Copy message": "复制消息",
        "Edit message": "编辑消息",
        "Delete message": "删除消息",
        "Message": "消息",
        "Response": "回应",
        "User": "用户",
        "Assistant": "助手",
        "System": "系统",
        "Tokens": "tokens",
        "Token usage": "token使用量",
        "Input tokens": "输入tokens",
        "Output tokens": "输出tokens",
        "Total tokens": "总tokens",

        // 发现页
        "Trending": "热门",
        "Recommended": "推荐",
        "Featured": "精选",
        "New": "最新",
        "Top rated": "最高评分",
        "Most used": "最多使用",
        "View details": "查看详情",
        "Try in chat": "在聊天中试用",

        // 账单和使用
        "Balance": "余额",
        "Add credits": "充值",
        "Add funds": "充值",
        "Payment method": "支付方式",
        "Billing history": "账单历史",
        "Usage summary": "使用汇总",
        "Usage by model": "按模型统计",
        "Daily usage": "每日使用",
        "Monthly usage": "每月使用",
        "Total spent": "总支出",
        "Cost": "费用",
        "Credits": "积分",
        "Amount": "金额",
        "Transaction": "交易",
        "Invoice": "发票",
        "Payment successful": "支付成功",
        "Payment failed": "支付失败",

        // 账户设置
        "Profile": "个人资料",
        "Settings": "设置",
        "Preferences": "偏好设置",
        "Notifications": "通知",
        "Security": "安全",
        "Connections": "连接",
        "Linked accounts": "关联账户",
        "Delete account": "删除账户",
        "Update profile": "更新资料",
        "Change password": "更改密码",
        "Current password": "当前密码",
        "New password": "新密码",
        "Update password": "更新密码",
        "Name": "姓名",
        "Username": "用户名",
        "Email": "邮箱",
        "Website": "网站",
        "Bio": "简介",
        "Avatar": "头像",
        "Upload avatar": "上传头像",
        "Remove avatar": "移除头像",
        "Time zone": "时区",
        "Language": "语言",
        "Theme": "主题",
        "Light": "浅色",
        "Dark": "深色",
        "Auto": "自动",

        // 付费方案
        "Free tier": "免费方案",
        "Pay as you go": "按需付费",
        "Enterprise": "企业方案",
        "Starting at": "起步价",
        "per month": "每月",
        "billed monthly": "按月计费",
        "billed annually": "按年计费",
        "Get started": "开始使用",
        "Contact sales": "联系销售",
        "Compare plans": "比较方案",
        "Features": "功能",
        "Included": "包含",
        "Not included": "不包含",
        "Limits": "限制",
        "Upgrade": "升级",
        "Downgrade": "降级",
        "Cancel subscription": "取消订阅",

        // 文档相关
        "Introduction": "介绍",
        "Getting Started": "快速开始",
        "API Reference": "API参考",
        "Authentication": "认证",
        "Rate Limits": "速率限制",
        "Error Codes": "错误代码",
        "FAQ": "常见问题",
        "Troubleshooting": "故障排除",
        "Examples": "示例",
        "Samples": "示例",
        "Quickstart": "快速开始",

        // 通用
        "Home": "主页",
        "Dashboard": "控制面板",
        "Help": "帮助",
        "Feedback": "反馈",
        "Report bug": "报告错误",
        "Version": "版本",
        "Build": "构建",
        "©": "©",
        "All rights reserved": "版权所有",
        "Powered by": "由提供支持",

        // 空状态和加载
        "No results": "无结果",
        "No data": "暂无数据",
        "Nothing here": "这里什么都没有",
        "Empty": "空",
        "No items": "无项目",
        "No chats": "无聊天",
        "No models": "无模型",
        "No API keys": "无API密钥",
        "No billing history": "无账单记录",
        "No usage data": "无使用数据",
        "Loading more": "加载更多...",
        "Load more": "加载更多",
        "Load failed": "加载失败",
        "Retry": "重试",

        // 确认对话框
        "Are you sure?": "确定吗?",
        "This action cannot be undone": "此操作无法撤销",
        "Are you sure you want to delete": "确定要删除吗?",
        "Delete permanently": "永久删除",
        "Continue anyway": "仍然继续",
        "Discard": "放弃",
        "Discard changes?": "放弃更改?",
        "You have unsaved changes": "您有未保存的更改",

        // 工具提示
        "Click to copy": "点击复制",
        "Copied!": "已复制!",
        "Download": "下载",
        "Open in new tab": "在新标签页打开",
        "Open link": "打开链接",
        "External link": "外部链接",

        // 通知和Toast
        "Notification": "通知",
        "Notifications": "通知",
        "Mark as read": "标为已读",
        "Mark all as read": "全部标为已读",
        "Dismiss": "关闭",
        "Close": "关闭",
        "Undo": "撤销",
        "Done": "完成",
        "OK": "确定",
        "Got it": "知道了",
    },
    "regexp": [
        [/OpenRouter - (.*)/, "OpenRouter - $1"],
        [/\/(Models|Chat|Discover|Account|API Keys|Billing|Usage|Pricing|Docs)\//i, " / $1 /"],
        [/Model cards?/i, "模型卡片"],
        [/API Documentation/i, "API文档"],
        [/Authentication & Security/i, "认证与安全"],
        [/Rate Limits/i, "速率限制"],
        [/Error Handling/i, "错误处理"],
        [/Best Practices/i, "最佳实践"],
        [/Code Examples/i, "代码示例"],
        [/Getting Started/i, "快速开始"],
        [/Welcome back!/i, "欢迎回来!"],
        [/Welcome to OpenRouter/i, "欢迎来到 OpenRouter"],
        [/Add credits? to your account/i, "为您的账户充值"],
        [/No credits?/i, "没有积分?"],
        [/Get (\d+) free credits/i, "获取 $1 免费积分"],
        [/completely free/i, "完全免费"],
        [/free tier/i, "免费方案"],
        [/billed monthly/i, "按月计费"],
        [/billed annually/i, "按年计费"],
        [/starting at/i, "起步价"],
        [/per 1K tokens/i, "每1K tokens"],
        [/context window/i, "上下文窗口"],
        [/tokens?/i, "tokens"],
        [/parameters/i, "参数"],
        [/billion parameters/i, "B 参数"],
        [/GPT-4/i, "GPT-4"],
        [/Claude/i, "Claude"],
        [/Llama/i, "Llama"],
        [/Gemini/i, "Gemini"],
        [/Mixtral/i, "Mixtral"],
        [/Mistral/i, "Mistral"],
        [/AI21/i, "AI21"],
        [/Cohere/i, "Cohere"],
        [/Command/i, "Command"],
        [/Jurassic/i, "Jurassic"],
        ["_regexp_end", "end"]
    ],
    "selector": [
        // 导航栏
        ["nav[aria-label='Primary'] a[href='/models']", "模型列表"],
        ["nav[aria-label='Primary'] a[href='/chat']", "聊天"],
        ["nav[aria-label='Primary'] a[href='/discover']", "发现"],
        ["nav[aria-label='Primary'] a[href='/account']", "账户"],
        ["nav a[href='/pricing']", "价格"],
        ["nav a[href='/docs']", "文档"],
        ["nav a[href='/login']", "登录"],
        ["nav a[href='/signup']", "注册"],

        // 页脚
        ["footer a[href='/about']", "关于"],
        ["footer a[href='/blog']", "博客"],
        ["footer a[href='/careers']", "招聘"],
        ["footer a[href='/terms']", "服务条款"],
        ["footer a[href='/privacy']", "隐私政策"],
        ["footer a[href='/security']", "安全"],
        ["footer a[href='/status']", "状态"],
        ["footer a[href='/community']", "社区"],
        ["footer a[href='/contact']", "联系我们"],

        // 按钮
        ["button[type='submit']", "提交"],
        ["button[type='button']:contains('Cancel')", "取消"],
        ["button[type='button']:contains('Save')", "保存"],
        ["button[type='button']:contains('Delete')", "删除"],
        ["button[type='button']:contains('Edit')", "编辑"],
        ["button[type='button']:contains('Create')", "创建"],
        ["button[type='button']:contains('Copy')", "复制"],
        ["button[type='button']:contains('Close')", "关闭"],
        ["button:contains('Add Credits')", "充值"],
        ["button:contains('Add Funds')", "充值"],
        ["button:contains('Sign In')", "登录"],
        ["button:contains('Sign Up')", "注册"],
        ["button:contains('Log out')", "退出登录"],
        ["button:contains('Send')", "发送"],
        ["a:contains('Try in chat')", "在聊天中试用"],
        ["a:contains('View details')", "查看详情"],
        ["a:contains('Learn more')", "了解更多"],

        // 标签和标题
        ["h1:contains('Models')", "模型列表"],
        ["h1:contains('Chat')", "聊天"],
        ["h1:contains('Discover')", "发现"],
        ["h1:contains('Account')", "账户"],
        ["h1:contains('API Keys')", "API密钥"],
        ["h1:contains('Billing')", "账单"],
        ["h1:contains('Usage')", "使用统计"],
        ["h1:contains('Pricing')", "价格"],

        // 表单标签
        ["label:contains('Email')", "邮箱"],
        ["label:contains('Password')", "密码"],
        ["label:contains('Confirm password')", "确认密码"],
        ["label:contains('Name')", "姓名"],
        ["label:contains('Username')", "用户名"],
        ["label:contains('Bio')", "简介"],
        ["label:contains('Key name')", "密钥名称"],
        ["label:contains('API Key')", "API密钥"],
        ["label:contains('Model')", "模型"],
        ["label:contains('Message')", "消息"],
        ["label:contains('System prompt')", "系统提示"],
        ["label:contains('Temperature')", "温度"],
        ["label:contains('Max tokens')", "最大tokens"],
        ["label:contains('Top P')", "Top P"],
        ["label:contains('Stop sequences')", "停止序列"],

        // 占位符
        ["input[placeholder*='Search models']", "搜索模型..."],
        ["input[placeholder*='Search']", "搜索..."],
        ["input[placeholder*='email']", "输入邮箱..."],
        ["input[placeholder*='password']", "输入密码..."],
        ["textarea[placeholder*='message']", "输入消息..."],

        // 通用
        [".loading-spinner", "加载中..."],
        [".error-message", "错误信息"],
        [".success-message", "成功"],
        [".warning-message", "警告"],
        [".empty-state", "空状态"],
    ]
};

// 页面特定词库
I18N["zh-CN"]["chat"] = {
    "static": {
        "New Chat": "新建聊天",
        "Chat history": "聊天记录",
        "No messages yet": "还没有消息",
        "Start typing your message": "开始输入消息",
        "Clear conversation": "清空对话",
        "Delete conversation": "删除对话",
        "Rename conversation": "重命名对话",
        "Export conversation": "导出对话",
        "Share chat": "分享聊天",
        "Model settings": "模型设置",
        "Advanced settings": "高级设置",
        "Context length": "上下文长度",
        "Stop generation": "停止生成",
        "Continue generation": "继续生成",
        "Streaming": "流式输出",
        "Stream": "流式",
        "Temperature": "温度",
        "Top P": "Top P",
        "Frequency penalty": "频率惩罚",
        "Presence penalty": "存在惩罚",
        "Max tokens": "最大tokens",
        "Stop sequences": "停止序列",
        "One per line": "每行一个",
        "System prompt": "系统提示",
        "Customize the AI's behavior": "自定义AI行为",
        "Tokens used": "已使用tokens",
        "Cost estimate": "费用估算",
        "About": "关于",
    },
    "regexp": [
        [/Chat with (.*)/i, "与 $1 聊天"],
        [/(.*) - Chat/i, "$1 - 聊天"],
        [/New chat with (.*)/i, "与 $1 新建聊天"],
        ["_regexp_end", "end"]
    ]
};

I18N["zh-CN"]["models"] = {
    "static": {
        "Search models": "搜索模型",
        "Filter by capability": "按能力过滤",
        "Filter by context length": "按上下文长度过滤",
        "Filter by pricing": "按价格过滤",
        "Sort by": "排序方式",
        "All Models": "全部模型",
        "Featured": "精选推荐",
        "Most popular": "最受欢迎",
        "Recently added": "最新添加",
        "Free": "免费",
        "Context window": "上下文窗口",
        "Price": "价格",
        "Input": "输入",
        "Output": "输出",
        "per 1K tokens": "每1K tokens",
        "View details": "查看详情",
        "Try in chat": "在聊天中试用",
        "No models found": "未找到模型",
        "Showing": "显示",
        "of": "个",
        "models": "模型",
    },
    "regexp": [
        [/(\d+) tokens?/i, "$1 tokens"],
        [/(\d+)k tokens?/i, "$1K tokens"],
        [/(\d+(?:\.\d+)?) ?B parameters/i, "$1B 参数"],
        ["_regexp_end", "end"]
    ]
};

I18N["zh-CN"]["discover"] = {
    "static": {
        "Trending models": "热门模型",
        "Recommended for you": "为您推荐",
        "Featured models": "精选模型",
        "New models": "新模型",
        "Top rated": "最高评分",
        "Most used": "最常用",
        "Explore": "探索",
        "Categories": "分类",
        "All categories": "全部分类",
        "Text generation": "文本生成",
        "Code generation": "代码生成",
        "Image generation": "图像生成",
        "Audio processing": "音频处理",
        "Video processing": "视频处理",
        "Multimodal": "多模态",
    }
};

I18N["zh-CN"]["account"] = {
    "static": {
        "Account Settings": "账户设置",
        "Profile": "个人资料",
        "Preferences": "偏好设置",
        "Notifications": "通知",
        "Security": "安全",
        "Connected Apps": "已连接应用",
        "Delete Account": "删除账户",
        "Update Profile": "更新资料",
        "Change Password": "更改密码",
        "Current password": "当前密码",
        "New password": "新密码",
        "Confirm new password": "确认新密码",
        "Update password": "更新密码",
        "Full name": "姓名",
        "Display name": "显示名称",
        "Username": "用户名",
        "Email address": "邮箱地址",
        "Website URL": "网站URL",
        "Bio": "个人简介",
        "Avatar": "头像",
        "Upload new avatar": "上传新头像",
        "Remove current avatar": "移除当前头像",
        "Time zone": "时区",
        "Language": "语言",
        "Interface language": "界面语言",
        "Theme": "主题",
        "Light theme": "浅色主题",
        "Dark theme": "深色主题",
        "System default": "系统默认",
        "Save changes": "保存更改",
        "Cancel": "取消",
    }
};

I18N["zh-CN"]["api-keys"] = {
    "static": {
        "API Keys": "API密钥",
        "Create API Key": "创建API密钥",
        "Your API Keys": "您的API密钥",
        "No API keys yet": "还没有API密钥",
        "Create your first key": "创建第一个密钥",
        "Key name": "密钥名称",
        "Enter a name for your key": "输入密钥名称",
        "Create": "创建",
        "Delete": "删除",
        "Are you sure you want to delete this API key?": "确定要删除此API密钥吗?",
        "This action cannot be undone": "此操作无法撤销",
        "The key will be permanently removed": "密钥将被永久删除",
        "Copy": "复制",
        "Copied!": "已复制!",
        "Never used": "从未使用",
        "Last used": "最后使用",
        "Created": "创建时间",
        "Created on": "创建于",
        "Status": "状态",
        "Active": "激活",
        "Revoked": "已撤销",
        "Show key": "显示密钥",
        "Hide key": "隐藏密钥",
        "API key": "API密钥",
        "Revoke": "撤销",
        "Regenerate": "重新生成",
    }
};

I18N["zh-CN"]["billing"] = {
    "static": {
        "Billing": "账单",
        "Add Credits": "充值",
        "Add Funds": "充值",
        "Balance": "余额",
        "Current Balance": "当前余额",
        "Payment Methods": "支付方式",
        "Add Payment Method": "添加支付方式",
        "Billing History": "账单历史",
        "Invoice": "发票",
        "Invoices": "发票",
        "Date": "日期",
        "Amount": "金额",
        "Status": "状态",
        "Paid": "已支付",
        "Pending": "待处理",
        "Failed": "失败",
        "Download": "下载",
        "Download invoice": "下载发票",
        "No billing history": "暂无账单记录",
        "No invoices": "暂无发票",
        "Add credits to your account": "为账户充值",
        "Choose amount": "选择金额",
        "Minimum": "最低",
        "or more": "或更多",
        "Continue": "继续",
        "Checkout": "结算",
        "Complete payment": "完成支付",
        "Payment successful": "支付成功",
        "Payment failed": "支付失败",
        "Something went wrong": "出错了",
        "Please try again": "请重试",
        "Return to billing": "返回账单页面",
    }
};

I18N["zh-CN"]["usage"] = {
    "static": {
        "Usage": "使用统计",
        "Usage Summary": "使用汇总",
        "Daily Usage": "每日使用",
        "Monthly Usage": "每月使用",
        "Total spent": "总支出",
        "Cost breakdown": "费用明细",
        "No usage data yet": "暂无使用数据",
        "Start using the API to see your usage metrics": "开始使用API以查看使用指标",
        "Date": "日期",
        "Model": "模型",
        "Input tokens": "输入tokens",
        "Output tokens": "输出tokens",
        "Total tokens": "总tokens",
        "Cost": "费用",
        "Export CSV": "导出CSV",
        "Last 7 days": "最近7天",
        "Last 30 days": "最近30天",
        "This month": "本月",
        "Custom range": "自定义范围",
        "From": "从",
        "To": "到",
        "Apply": "应用",
        "Reset": "重置",
        "Loading usage data": "加载使用数据...",
    }
};

I18N["zh-CN"]["auth"] = {
    "static": {
        "Sign In": "登录",
        "Sign Up": "注册",
        "Email": "邮箱",
        "Password": "密码",
        "Confirm password": "确认密码",
        "Forgot password?": "忘记密码?",
        "Reset password": "重置密码",
        "Send reset link": "发送重置链接",
        "Verification code": "验证码",
        "Enter verification code": "输入验证码",
        "Verify": "验证",
        "Two-factor authentication": "双因素认证",
        "Enter 6-digit code": "输入6位验证码",
        "Remember this device": "记住此设备",
        "Don't have an account?": "还没有账户?",
        "Already have an account?": "已有账户?",
        "Sign up": "注册",
        "Create account": "创建账户",
        "By signing up, you agree to our": "注册即表示您同意我们的",
        "Terms of Service": "服务条款",
        "and": "和",
        "Privacy Policy": "隐私政策",
        "Or continue with": "或继续使用",
        "Google": "Google",
        "GitHub": "GitHub",
        "Microsoft": "Microsoft",
        "Sign in with": "登录方式",
        "Invalid email or password": "邮箱或密码无效",
        "Invalid verification code": "验证码无效",
        "Password too weak": "密码太弱",
        "Passwords do not match": "密码不匹配",
        "Account created successfully": "账户创建成功",
        "Check your email": "检查您的邮箱",
        "Email not verified": "邮箱未验证",
        "Resend verification email": "重新发送验证邮件",
    }
};

I18N["zh-CN"]["homepage"] = {
    "static": {
        "OpenRouter - AI API统一接口": "OpenRouter - AI API统一接口",
        "Access all AI models through a single API": "通过单一API访问所有AI模型",
        "Start building with the world's best AI": "开始使用世界顶级AI进行构建",
        "Get Started Free": "免费开始",
        "No credit card required": "无需信用卡",
        "Features": "功能特点",
        "One API for all models": "所有模型统一API",
        "Simple integration": "简单集成",
        "Best pricing": "最优价格",
        "Enterprise-ready": "企业级就绪",
        "Popular models": "热门模型",
        "Try in browser": "在浏览器中试用",
        "What developers say": "开发者评价",
        "Pricing": "价格",
        "Simple, transparent pricing": "简单透明定价",
        "Free tier": "免费方案",
        "Pay as you go": "按需付费",
        "Enterprise": "企业方案",
        "View all models": "查看全部模型",
        "View pricing": "查看价格",
        "Contact sales": "联系销售",
        "docs": "文档",
        "API reference": "API参考",
        "Guides": "指南",
        "Examples": "示例",
        "Resources": "资源",
        "Community": "社区",
        "Support": "支持",
        "Blog": "博客",
        "Changelog": "更新日志",
        "Status": "状态",
        "©": "©",
        "All rights reserved": "版权所有",
    }
};

I18N["zh-CN"]["generic"] = {
    "static": {
        "Loading...": "加载中...",
        "Error loading": "加载失败",
        "Retry": "重试",
        "No results found": "未找到结果",
        "Search": "搜索",
        "Filter": "过滤",
        "Sort": "排序",
        "Apply": "应用",
        "Reset": "重置",
        "Clear": "清空",
        "All": "全部",
        "None": "无",
        "Yes": "是",
        "No": "否",
        "On": "开",
        "Off": "关",
        "Enable": "启用",
        "Disable": "禁用",
        "Confirm": "确认",
        "Cancel": "取消",
        "Save": "保存",
        "Delete": "删除",
        "Edit": "编辑",
        "Create": "创建",
        "Copy": "复制",
        "Paste": "粘贴",
        "Cut": "剪切",
        "Undo": "撤销",
        "Redo": "重做",
        "Select all": "全选",
        "Deselect all": "取消全选",
        "Expand": "展开",
        "Collapse": "收起",
        "Show more": "显示更多",
        "Show less": "显示更少",
        "View": "查看",
        "Download": "下载",
        "Upload": "上传",
        "Import": "导入",
        "Export": "导出",
        "Print": "打印",
        "Share": "分享",
        "Link copied": "链接已复制",
        "Failed to copy": "复制失败",
    }
};
